# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a873f2b4d42ec80bbcaea6adbe8fce4e520e9417f393dd805cad7964428de73c62eb3f59f7b57b7fb44692af77b5cb57bf213957446346f3c1c99833bd14e0ba

test:
  secret_key_base: 1e7560c32fa5620489e2eeac3077c8fb5723c99f67cd4bf47959436e2940598ba42376639df53548b022eb1dd089ab337142f98e6e6f581504fb6ce333fb8a2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
